### ISSUE TITLE
error for qt5-default not supported on humble 

### ISSUE THREAD

**Issue by ncnynl** [open-rmf/free_fleet#125] opened 2022-12-02 14:28 UTC
qt5-default not supported on humble .I have not installed qt5-default, it seems that the installation has no effect, and the use has no effect, but my system has installed python3-pyqt5

**Comment by aaronchongth** [comment] 2022-12-02 15:41
Closing this as it is not a bug or issue related to free_fleet.

In the future, please describe the exact scenario, system and situation you are encountering issues with

**Closed by aaronchongth** 2022-12-02 15:41 UTC
Labels: bug

**Comment by ncnynl** [comment] 2022-12-03 02:03
Sorry for not providing a more detailed description
This problem occurs during the installation step, 
on the web page https://github.com/open-rmf/free_fleet . 
The code is:

```
sudo apt update && sudo apt install \
  git wget qt5-default \
  python3-rosdep \
  python3-vcstool \
  python3-colcon-common-extensions \
  # maven default-jdk   # Uncomment to install dependencies for message generation
```

There is currently no special installation introduction for humble base on ubuntu22.04, I installed it according to the latest version. 

Because ubuntu22.04 does not have the qt5-default package, executing the above command will provide an error

**Comment by aaronchongth** [comment] 2022-12-05 02:06
I see what you mean. There has certainly been a lapse in documentation as we moved to Humble. Would you like to open a PR to correct the documentation?
